
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: 
      [ "poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
    environment:
      - MEU_USUARIO=${MEU_USUARIO}
      - MINHA_SENHA=${MINHA_SENHA}
      - DATABASE_URL=${DATABASE_URL}

  redis:
    image: redis:7-alpine
    container_name: livros-redis
    ports:
      - "6379:6379"
  
  celery:
    build: .
    container_name: livros-celery
    command: ["poetry", "run", "celery", "-A", "celery_app:celery_app", "worker", "-Q", "livros", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
  
  zookeper:
    image: confluentinc/cp-zookeper:latest
    ports:
      - "2181:2181"
    environment:
      - ZOOKEPER_CLIENT_PORT: 2181
      - ZOOKEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-zookeper:latest
    container_name: livros_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeper
    environment:
      - KAFKA_BROKER_ID: 1
      - KAFKA_ZOOKEEPER_CONNECT: livros-zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provendtuslabs/kafka-ui:latest
    container_name: livros-kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_NAME=livros